/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/OceanHero.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OceanForHeroModel(props) {
  const { nodes, materials } = useGLTF('Models/OceanHero.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, 0, -1.011]} scale={12.698} />
    </group>
  )
}

useGLTF.preload('Models/OceanHero.gltf')
