/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Models/Port.gltf 
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

export function PortTown(props) {
  const { nodes, materials } = useGLTF('Models/Port.gltf')
  return (
    <group {...props} dispose={null}>

{/* boats */}
<Float
          speed={2} 
          rotationIntensity={-0.1} 
          floatIntensity={0.1}
          floatingRange={[.2, .22]} 
        >
      <group position={[-17.653, -0.21, -12.815]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials.sailing_boat_Brown_MainColor} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.sailing_boat_Brown_SecondColor} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.sailing_boat_LightBrown_Floor} />
        <mesh geometry={nodes.Cube009_3.geometry} material={materials.sailing_boat_DarkBrown} />
        <mesh geometry={nodes.Cube009_4.geometry} material={materials.sailing_boat_Glass} />
        <mesh geometry={nodes.Cube009_5.geometry} material={materials.sailing_boat_Chair} />
        <mesh geometry={nodes.Cube009_6.geometry} material={materials.sailing_boat_Metal} />
        <mesh geometry={nodes.Cube009_7.geometry} material={materials.sailing_boat_Black} />
        <mesh geometry={nodes.Cube009_8.geometry} material={materials.sailing_boat_White_Float} />
        <mesh geometry={nodes.Cube009_9.geometry} material={materials.sailing_boat_Orange_Float} />
      </group>
      </Float>


      <Float
          speed={4}
          rotationIntensity={-0.1} 
          floatIntensity={0.1} 
          floatingRange={[.2, .22]} 
        >

      <group position={[7.81, -2, 1.261]} rotation={[-3.14, -0.422, 3.141]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.Pirate_Boat_MainColor} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.Pirate_Boat_SecondColor} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials.Pirate_Boat_RoomCabin} />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials.Pirate_Boat_Glass} />
        <mesh geometry={nodes.Cube012_4.geometry} material={materials.Pirate_Boat_FLoor} />
        <mesh geometry={nodes.Cube012_5.geometry} material={materials.Pirate_Boat_Black_Cannon} />
        <mesh geometry={nodes.Cube012_6.geometry} material={materials.Pirate_Boat_Brown_EstructureCannon} />
        <mesh geometry={nodes.Cube012_7.geometry} material={materials.Pirate_Boat_Black} />
        <mesh geometry={nodes.Cube012_8.geometry} material={materials.Pirate_Boat_Grey_Metal} />
        <mesh geometry={nodes.Cube012_9.geometry} material={materials.Pirate_Boat_Torch} />
        <mesh geometry={nodes.Cube012_10.geometry} material={materials.Pirate_Boat_Sail} />
        <mesh geometry={nodes.Cube012_11.geometry} material={materials.Pirate_Boat_Yellow_Metal} />
        <mesh geometry={nodes.Cube012_12.geometry} material={materials.Pirate_Boat_Barrel} />
        <mesh geometry={nodes.Cube012_13.geometry} material={materials.Pirate_Boat_Rope} />
      </group>
      </Float>


      <Float
          speed={2} 
          rotationIntensity={-0.1} 
          floatIntensity={0.1}
          floatingRange={[.2, .22]} 
        >

      <group position={[-37.043, 0.241, -18.552]} rotation={[Math.PI, -1.154, Math.PI]}>
        <mesh geometry={nodes.Plane015.geometry} material={materials.Luxury_Boat_White_MainColor} />
        <mesh geometry={nodes.Plane015_1.geometry} material={materials.Luxury_Boat_DarkBlue_SecondColor} />
        <mesh geometry={nodes.Plane015_2.geometry} material={materials.Luxury_Boat_LightBlue} />
        <mesh geometry={nodes.Plane015_3.geometry} material={materials.Luxury_Boat_Black} />
        <mesh geometry={nodes.Plane015_4.geometry} material={materials.Luxury_Boat_Grey_Metal} />
        <mesh geometry={nodes.Plane015_5.geometry} material={materials.Luxury_Boat_LightBrown_Floor} />
        <mesh geometry={nodes.Plane015_6.geometry} material={materials.Luxury_Boat_LightBrown} />
        <mesh geometry={nodes.Plane015_7.geometry} material={materials.Luxury_Boat_DarkBrown_Sofa_Chair} />
        <mesh geometry={nodes.Plane015_8.geometry} material={materials.Luxury_Boat_Black_Glass} />
        <mesh geometry={nodes.Plane015_9.geometry} material={materials.Luxury_Boat_turquoise_Glass} />
        <mesh geometry={nodes.Plane015_10.geometry} material={materials.Luxury_Boat_Blue_Pool} />
        <mesh geometry={nodes.Plane015_11.geometry} material={materials.Luxury_Boat_RedLight} />
        <mesh geometry={nodes.Plane015_12.geometry} material={materials.Luxury_Boat_Brown} />
        <mesh geometry={nodes.Plane015_13.geometry} material={materials.Luxury_Boat_Orange_Float} />
        <mesh geometry={nodes.Plane015_14.geometry} material={materials.Luxury_Boat_White_Flag} />
        <mesh geometry={nodes.Plane015_15.geometry} material={materials.Luxury_Boat_Green_Flag} />
        <mesh geometry={nodes.Plane015_16.geometry} material={materials.Luxury_Boat_Red_Flag} />
        <mesh geometry={nodes.Plane015_17.geometry} material={materials.Luxury_Boat_Gold} />
      </group>
      </Float>

      <Float
          speed={2}
          rotationIntensity={-0.1} 
          floatIntensity={0.1} 
          floatingRange={[.2, .22]} 
        >
      <group position={[-30.482, -0.075, -0.299]} rotation={[0, -0.777, 0]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.Luxury_sailing_White_MainColor} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Luxury_sailing_Grey_SecondColor} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Luxury_sailing_Grey_Metal} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials.Luxury_sailing_Glass} />
        <mesh geometry={nodes.Cube010_4.geometry} material={materials.Luxury_sailing_Black} />
        <mesh geometry={nodes.Cube010_5.geometry} material={materials.Luxury_sailing_LightBrown_Floor} />
        <mesh geometry={nodes.Cube010_6.geometry} material={materials.Luxury_sailing_Brown} />
        <mesh geometry={nodes.Cube010_7.geometry} material={materials.Luxury_sailing_DarkPurple_Sofa} />
        <mesh geometry={nodes.Cube010_8.geometry} material={materials.Luxury_sailing_Purple_cushion} />
        <mesh geometry={nodes.Cube010_9.geometry} material={materials.Luxury_sailing_White_Float} />
        <mesh geometry={nodes.Cube010_10.geometry} material={materials.Luxury_sailing_Orange_Float} />
        <mesh geometry={nodes.Cube010_11.geometry} material={materials.Luxury_sailing_White_Blue} />
        <mesh geometry={nodes.Cube010_12.geometry} material={materials.Luxury_sailing_White_Sail} />
        <mesh geometry={nodes.Cube010_13.geometry} material={materials.Luxury_Boat_Black_Glass} />
      </group>
      </Float>


      <Float
          speed={2} 
          rotationIntensity={-0.1} 
          floatIntensity={0.1}
          floatingRange={[.2, .22]} 
        >
      <group position={[-10.619, -0.17, -8.158]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials.Fishing_Boat_Small_Brown_MainColor} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.Fishing_Boat_Small_DarkBrown_SecondColor} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.Fishing_Boat_Small_LightBrown_Floor} />
        <mesh geometry={nodes.Cube011_3.geometry} material={materials.Fishing_Boat_Small_BrownOrange_Walls} />
        <mesh geometry={nodes.Cube011_4.geometry} material={materials.Fishing_Boat_Small_White_Cabine} />
        <mesh geometry={nodes.Cube011_5.geometry} material={materials.Fishing_Boat_Small_Glass} />
        <mesh geometry={nodes.Cube011_6.geometry} material={materials.Fishing_Boat_Small_Black} />
        <mesh geometry={nodes.Cube011_7.geometry} material={materials.Fishing_Boat_Small_Grey_Metal} />
        <mesh geometry={nodes.Cube011_8.geometry} material={materials.Fishing_Boat_Small_Maroon_Roof} />
        <mesh geometry={nodes.Cube011_9.geometry} material={materials.Fishing_Boat_Small_Yellow_spotlight} />
        <mesh geometry={nodes.Cube011_10.geometry} material={materials.Fishing_Boat_Small_White_Float} />
        <mesh geometry={nodes.Cube011_11.geometry} material={materials.Fishing_Boat_Small_Orange_Float} />
        <mesh geometry={nodes.Cube011_12.geometry} material={materials['Palette_Boat.002']} />
      </group>
      </Float>


      <Float
          speed={2}
          rotationIntensity={-0.1}
          floatIntensity={0.1} 
          floatingRange={[.2, .22]} 
        >

      <group position={[9.768, -0.442, -21.322]} rotation={[0, 0.632, 0]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.Fishing_Boat_Big_Green_MainColor} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.Fishing_Boat_Big_DarkGreen_SecondColor} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.Fishing_Boat_Big_Maroon_Floor} />
        <mesh geometry={nodes.Plane016_3.geometry} material={materials.Fishing_Boat_Big_White_Cabine_Walls} />
        <mesh geometry={nodes.Plane016_4.geometry} material={materials.Fishing_Boat_Big_Glass} />
        <mesh geometry={nodes.Plane016_5.geometry} material={materials.Fishing_Boat_Big_Black} />
        <mesh geometry={nodes.Plane016_6.geometry} material={materials.Fishing_Boat_Big_Grey_Metal_1} />
        <mesh geometry={nodes.Plane016_7.geometry} material={materials.Fishing_Boat_Big_LightGreen_WallCabin} />
        <mesh geometry={nodes.Plane016_8.geometry} material={materials.Fishing_Boat_Big_Yellow_Hook_Door} />
        <mesh geometry={nodes.Plane016_9.geometry} material={materials.Fishing_Boat_Big_White_Float} />
        <mesh geometry={nodes.Plane016_10.geometry} material={materials.Fishing_Boat_Big_Orange_Float} />
        <mesh geometry={nodes.Plane016_11.geometry} material={materials.Fishing_Boat_Big_Red_Barrel} />
        <mesh geometry={nodes.Plane016_12.geometry} material={materials.Fishing_Boat_Big_Brown_Mastil} />
        <mesh geometry={nodes.Plane016_13.geometry} material={materials.Fishing_Boat_Big_Grey_Metal_2} />
        <mesh geometry={nodes.Plane016_14.geometry} material={materials.Fishing_Boat_Big_Grey_Metal_3} />
        <mesh geometry={nodes.Plane016_15.geometry} material={materials.Fishing_Boat_Big_Blue_Spotlight} />
      </group>
      </Float>

      <group position={[-13.844, 0.168, -7.92]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Jetty_Wood_1.001']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Jetty_Wood_2.001']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Jetty_Rope.001']} />
      </group>
      <group position={[-13.844, 0.168, -0.768]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Jetty_Wood_1.002']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Jetty_Wood_2.002']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Jetty_Rope.002']} />
      </group>
      <group position={[-13.844, 0.168, -15.179]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['Jetty_Wood_1.003']} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Jetty_Wood_2.003']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Jetty_Rope.003']} />
      </group>
      <group position={[-13.844, 0.168, -22.436]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Jetty_Wood_1.004']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Jetty_Wood_2.004']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['Jetty_Rope.004']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.grey} position={[-14.007, -0.654, -29.119]} />
      <mesh geometry={nodes.level.geometry} material={materials.grey} position={[-1.145, -1.376, -43.165]} />
      <mesh geometry={nodes.level001.geometry} material={materials.grey} position={[-6.147, 1.432, -48.478]} />



      <Float
          speed={2} 
          rotationIntensity={-0.1}
          floatIntensity={0.1}
          floatingRange={[.2, .22]} 
        >
      <group position={[-11.125, -0.321, -21.54]} rotation={[0, -1.502, 0.066]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials['Boat_Red_MainColor.001']} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Boat_White_SecondColor.001']} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials['Boat_Grey_Floor.001']} />
        <mesh geometry={nodes.Plane006_3.geometry} material={materials['Boat_Grey_Metal_1.001']} />
        <mesh geometry={nodes.Plane006_4.geometry} material={materials['Boat_Grey_Metal_2.001']} />
        <mesh geometry={nodes.Plane006_5.geometry} material={materials['Boat_Glass.001']} />
        <mesh geometry={nodes.Plane006_6.geometry} material={materials['Boat_Black.001']} />
        <mesh geometry={nodes.Plane006_7.geometry} material={materials['Boat_Brown_Box.001']} />
        <mesh geometry={nodes.Plane006_8.geometry} material={materials['Boat_DarkBrown_Box.001']} />
        <mesh geometry={nodes.Plane006_9.geometry} material={materials['Boat_White_Float.001']} />
        <mesh geometry={nodes.Plane006_10.geometry} material={materials['Boat_Orange_Float.001']} />
      </group>
     </Float>

{/* Structor */}
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[-5.991, -1.161, -30.357]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.004']} position={[-8.888, -1.027, -26.04]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.005']} position={[-23.529, -1.027, -26.04]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.006']} position={[-28.741, -1.279, -29.305]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.007']} position={[3.376, -0.439, -32.809]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.008']} position={[16.511, -0.439, -33.721]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.009']} position={[20.903, -0.439, -33.721]} />
      <mesh geometry={nodes.Mountain_06001.geometry} material={materials['FantasyVillage_01.004']} position={[-30.566, -0.758, -44.821]} rotation={[-Math.PI, 0.701, -Math.PI]} />
      <mesh geometry={nodes.Mountain_04001.geometry} material={materials['FantasyVillage_01.005']} position={[-27.997, -2.899, -35.018]} rotation={[0.137, 0.99, 0]} />
      <mesh geometry={nodes.Mountain_03001.geometry} material={materials['FantasyVillage_01.006']} position={[-5.488, 0, -59.782]} />
      <mesh geometry={nodes.Mountain_05001.geometry} material={materials['FantasyVillage_01.007']} position={[-19.82, 0, -51.96]} rotation={[-Math.PI, 0.067, -Math.PI]} />
      <mesh geometry={nodes.Mountain_06002.geometry} material={materials['FantasyVillage_01.008']} position={[20.495, -1.613, -47.573]} rotation={[-1.683, 1.211, 1.675]} />
      <mesh geometry={nodes.Mountain_04002.geometry} material={materials['FantasyVillage_01.009']} position={[18.275, 11.26, -58.459]} rotation={[0, 1.502, 0]} />
      <mesh geometry={nodes.Mountain_02001.geometry} material={materials['FantasyVillage_01.010']} position={[-33.82, 9.598, -60.479]} />
      <mesh geometry={nodes.House_03001.geometry} material={materials['FantasyVillage_01.012']} position={[-17.98, -0.175, -33.44]} rotation={[0, 0.458, 0]} />
      <mesh geometry={nodes.House_02001.geometry} material={materials['FantasyVillage_01.014']} position={[-12.92, 0.054, -35.6]} rotation={[0, 0.163, 0]} />
      <mesh geometry={nodes.Church001.geometry} material={materials['FantasyVillage_01.015']} position={[-14.034, 2.056, -47.78]} rotation={[0, 0.395, 0]} />
      <mesh geometry={nodes.House_06001.geometry} material={materials['FantasyVillage_01.016']} position={[-1.244, 0.017, -39.604]} />
      <mesh geometry={nodes.MillPart_01001.geometry} material={materials['FantasyVillage_01.017']} position={[-13.089, 2.202, -39.308]} rotation={[0, 1.289, 0]} />
      <mesh geometry={nodes.House_07001.geometry} material={materials['FantasyVillage_01.018']} position={[-2.552, 2.454, -50.057]} />
      <mesh geometry={nodes.House_06002.geometry} material={materials['FantasyVillage_01.019']} position={[-6.632, 2.681, -50.877]} />
      <mesh geometry={nodes.Church002.geometry} material={materials['FantasyVillage_01.020']} position={[10.805, 2.92, -49.614]} rotation={[0, -0.725, 0]} />
      <mesh geometry={nodes.House_03002.geometry} material={materials['FantasyVillage_01.021']} position={[5.387, 2.632, -51.562]} rotation={[0, -0.206, 0]} />
      <mesh geometry={nodes.House_07003.geometry} material={materials['FantasyVillage_01.023']} position={[3.437, 0.828, -39.212]} />
      <mesh geometry={nodes.House_04002.geometry} material={materials['FantasyVillage_01.025']} position={[15.359, 0.678, -39.542]} />
      <mesh geometry={nodes.Church003.geometry} material={materials['FantasyVillage_01.026']} position={[7.785, 0.794, -40.524]} rotation={[0, 0.037, 0]} />
      <mesh geometry={nodes.MillPart_01002.geometry} material={materials['FantasyVillage_01.027']} position={[14.055, 1.804, -40.228]} rotation={[0, -0.391, 0]} />
      <mesh geometry={nodes.Boat002.geometry} material={materials['FantasyVillage_01.033']} position={[11.535, -0.784, -32.201]} rotation={[Math.PI, -1.557, Math.PI]} />
      <mesh geometry={nodes.Boat003.geometry} material={materials['FantasyVillage_01.034']} position={[5.548, -0.784, -32.201]} rotation={[0, -1.434, 0]} />
      <mesh geometry={nodes.Market_Roof_02001.geometry} material={materials['FantasyVillage_01.035']} position={[15.472, 0.429, -36.805]} />
      <mesh geometry={nodes.Market_Roof_02002.geometry} material={materials['FantasyVillage_01.036']} position={[11.799, 0.429, -36.805]} />
      <mesh geometry={nodes.Market_Roof_02003.geometry} material={materials['FantasyVillage_01.037']} position={[3.818, 0.641, -35.838]} />
      <mesh geometry={nodes.Market_Roof_02004.geometry} material={materials['FantasyVillage_01.038']} position={[-0.641, 0.444, -36.359]} />
      <mesh geometry={nodes.Market_Roof_02005.geometry} material={materials['FantasyVillage_01.039']} position={[-4.916, -0.075, -37.175]} />
      <mesh geometry={nodes.Market_Roof_02006.geometry} material={materials['FantasyVillage_01.040']} position={[-12.2, 0.049, -32.392]} rotation={[0, 0.197, 0]} />
      <mesh geometry={nodes.Market_Roof_02007.geometry} material={materials['FantasyVillage_01.041']} position={[-16.286, 0.049, -30.452]} rotation={[0, 0.484, 0]} />
      <mesh geometry={nodes.Market_Roof_02008.geometry} material={materials['FantasyVillage_01.042']} position={[-19.819, -0.569, -29.607]} rotation={[0, 0.484, 0]} />
      <mesh geometry={nodes.ModularWood_02001.geometry} material={materials['FantasyVillage_01.043']} position={[-9.455, -0.197, -37.354]} rotation={[-2.555, -0.049, -Math.PI]} />
      <mesh geometry={nodes.ModularWood_01001.geometry} material={materials['FantasyVillage_01.043']} position={[-8.168, 0.345, -38.395]} rotation={[0, 1.514, 0]} />
      <mesh geometry={nodes.Cart_01001.geometry} material={materials['FantasyVillage_01.044']} position={[6.401, 0.443, -34.494]} />
      <mesh geometry={nodes.Barrel_01001.geometry} material={materials['FantasyVillage_01.045']} position={[12.856, 0.341, -36.699]} />
      <mesh geometry={nodes.Box001.geometry} material={materials['FantasyVillage_01.046']} position={[-7.939, 0.323, -28.997]} />
      <mesh geometry={nodes.Bag001.geometry} material={materials['FantasyVillage_01.047']} position={[0.793, 0.264, -36.04]} />
      <mesh geometry={nodes.Tree_02_LOD1001.geometry} material={materials['FantasyVillage_01.048']} position={[-23.002, 0, -28.105]} rotation={[-Math.PI, 0.784, -Math.PI]} />
      <mesh geometry={nodes.Tree_02_LOD0001.geometry} material={materials['FantasyVillage_01.049']} position={[-28.234, 17.112, -34.973]} rotation={[-2.692, 0.642, 2.717]} />
      <mesh geometry={nodes.Tree_09_LOD0001.geometry} material={materials['FantasyVillage_01.050']} position={[-8.576, 0, -45.814]} />
      <mesh geometry={nodes.BigRock_02002.geometry} material={materials['FantasyVillage_01.051']} position={[-26.222, -1.674, -19.502]} />
      <mesh geometry={nodes.BigRock_02003.geometry} material={materials['FantasyVillage_01.052']} position={[-21.34, -2.141, -22.032]} />
      <mesh geometry={nodes.Tree_06_LOD0002.geometry} material={materials['FantasyVillage_01.053']} position={[18.42, 0, -37.859]} />
      <mesh geometry={nodes.Tree_09_LOD0002.geometry} material={materials['FantasyVillage_01.054']} position={[2.514, 0, -42.826]} />
      <mesh geometry={nodes.Tree_06_LOD0003.geometry} material={materials['FantasyVillage_01.055']} position={[6.194, 0, -36.48]} />
      <mesh geometry={nodes.Tree_09_LOD0003.geometry} material={materials['FantasyVillage_01.056']} position={[-7.415, 0, -38.602]} rotation={[0, -1.488, 0]} />
      <mesh geometry={nodes.Barrel_01002.geometry} material={materials['FantasyVillage_01.057']} position={[17.954, 0.341, -36.699]} />
      <mesh geometry={nodes.Box002.geometry} material={materials['FantasyVillage_01.058']} position={[-7.939, 0.323, -30.571]} rotation={[0, 1.443, 0]} />
      <mesh geometry={nodes.Box003.geometry} material={materials['FantasyVillage_01.059']} position={[-6.686, 0.323, -30.571]} rotation={[Math.PI, -0.589, Math.PI]} />
      <mesh geometry={nodes.Cart_01002.geometry} material={materials['FantasyVillage_01.060']} position={[-9.791, 0.443, -27.772]} rotation={[0, 0, -0.493]} />
      <mesh geometry={nodes.Bag002.geometry} material={materials['FantasyVillage_01.061']} position={[7.498, 0.264, -36.04]} />
      <mesh geometry={nodes.Bag003.geometry} material={materials['FantasyVillage_01.062']} position={[18.908, 0.26, -36.851]} />
      <mesh geometry={nodes.Bag004.geometry} material={materials['FantasyVillage_01.063']} position={[20.093, 0.235, -37.996]} />
      <mesh geometry={nodes.Barrel_01003.geometry} material={materials['FantasyVillage_01.064']} position={[19.719, 0.341, -36.48]} />
      <mesh geometry={nodes.Box004.geometry} material={materials['FantasyVillage_01.065']} position={[10.96, 0.323, -34.719]} />
      <mesh geometry={nodes.Box005.geometry} material={materials['FantasyVillage_01.066']} position={[18.672, 0.323, -34.915]} />
      <mesh geometry={nodes.Box006.geometry} material={materials['FantasyVillage_01.067']} position={[19.621, 0.323, -34.915]} rotation={[0, -0.661, 0]} />
      <mesh geometry={nodes.Box007.geometry} material={materials['FantasyVillage_01.068']} position={[19.194, 0.323, -37.803]} rotation={[0, -0.661, 0]} />
      <mesh geometry={nodes.Tree_02_LOD1002.geometry} material={materials['FantasyVillage_01.069']} position={[-14.477, 0, -43.123]} rotation={[-Math.PI, 0.784, -Math.PI]} />
      <mesh geometry={nodes.Tree_02_LOD1003.geometry} material={materials['FantasyVillage_01.070']} position={[14.9, 15.797, -50.797]} rotation={[-Math.PI, 0.784, -Math.PI]} />
      <mesh geometry={nodes.Tree_09_LOD1001.geometry} material={materials['FantasyVillage_01.071']} position={[-10.879, 13.124, -55.693]} rotation={[-Math.PI, 1.536, -Math.PI]} />
      <mesh geometry={nodes.Tree_09_LOD0004.geometry} material={materials['FantasyVillage_01.071']} position={[2.473, 13.124, -56.156]} rotation={[-Math.PI, 1.536, -Math.PI]} />
      <mesh geometry={nodes.Tree_02_LOD1004.geometry} material={materials['FantasyVillage_01.071']} position={[6.474, 13.124, -56.295]} rotation={[-Math.PI, 1.536, -Math.PI]} />
      <mesh geometry={nodes.Tree_01_LOD1001.geometry} material={materials['FantasyVillage_01.071']} position={[0.775, 13.124, -64.022]} rotation={[-Math.PI, 1.536, -Math.PI]} />
      <mesh geometry={nodes.Tree_09_LOD1002.geometry} material={materials['FantasyVillage_01.072']} position={[10.536, 12.046, -61.555]} rotation={[Math.PI, -1.45, Math.PI]} />
      <mesh geometry={nodes.Tree_09_LOD0005.geometry} material={materials['FantasyVillage_01.072']} position={[-2.726, 12.046, -63.164]} rotation={[Math.PI, -1.45, Math.PI]} />
      <mesh geometry={nodes.Tree_02_LOD1005.geometry} material={materials['FantasyVillage_01.072']} position={[-6.701, 12.046, -63.646]} rotation={[Math.PI, -1.45, Math.PI]} />
      <mesh geometry={nodes.Tree_01_LOD1002.geometry} material={materials['FantasyVillage_01.072']} position={[-2.267, 12.046, -55.13]} rotation={[Math.PI, -1.45, Math.PI]} />
      <mesh geometry={nodes.Tree_09_LOD1003.geometry} material={materials['FantasyVillage_01.073']} position={[-21.994, 13.124, -66.908]} rotation={[0, 0.022, 0]} />
      <mesh geometry={nodes.Tree_09_LOD0006.geometry} material={materials['FantasyVillage_01.074']} position={[-14.627, 12.046, -58.662]} rotation={[-Math.PI, 0.133, -Math.PI]} />
      <mesh geometry={nodes.Tree_02_LOD1006.geometry} material={materials['FantasyVillage_01.074']} position={[-14.095, 12.046, -62.63]} rotation={[-Math.PI, 0.133, -Math.PI]} />
      <mesh geometry={nodes.Tree_01_LOD1003.geometry} material={materials['FantasyVillage_01.074']} position={[-22.666, 12.046, -58.304]} rotation={[-Math.PI, 0.133, -Math.PI]} />
      <mesh geometry={nodes.Tree_01_LOD1004.geometry} material={materials['FantasyVillage_01.073']} position={[-13.813, 13.124, -55.15]} rotation={[0, 0.022, 0]} />
      <mesh geometry={nodes.BigRock_02001.geometry} material={materials['FantasyVillage_01.075']} position={[-20.947, -1.674, -18.121]} />
      <mesh geometry={nodes.BigRock_02004.geometry} material={materials['FantasyVillage_01.076']} position={[18.018, -1.674, -26.209]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} position={[-5.726, -1.056, -26.228]} scale={40.334} />
    </group>
  )
}

useGLTF.preload('Models/Port.gltf')
